<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows10.0.22000.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
		<RootNamespace>DrillMagic.Windows</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<Platforms>x86;x64;ARM64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<UseWinUI>true</UseWinUI>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<Content Remove="Resources\Logo.png" />
	</ItemGroup>
	<ItemGroup>
		<None Remove="Controls\ColorSummaryLegend.xaml" />
		<None Remove="DrillGridView.xaml" />
		<None Remove="Resources\Logo.ico" />
	</ItemGroup>
	<ItemGroup>
		<Content Include="Resources\Logo.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\Logo.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CommunityToolkit.WinUI.Controls.TabbedCommandBar" Version="8.2.250402" />
		<PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
		<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4948" />
		<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250916003" />
		<PackageReference Include="WinUIEx" Version="2.8.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\DrillMagic.Core\DrillMagic.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Page Update="Controls\DrillGridView.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\Logo.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	<ItemGroup>
		<Page Update="Controls\ColorSummaryLegend.xaml">
			<Generator>MSBuild:Compile</Generator>
		</Page>
	</ItemGroup>
	<!-- Publish Properties -->
	<PropertyGroup>
		<PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
		<PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
		<PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
		<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PackageIcon>Logo.png</PackageIcon>
	</PropertyGroup>
</Project>