name: .NET Tests

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore DrillMagic.Test/DrillMagic.Test.csproj
    - name: Build
      run: dotnet build DrillMagic.Test/DrillMagic.Test.csproj --no-restore
    - name: Test
      run: dotnet test DrillMagic.Test/DrillMagic.Test.csproj --no-build --verbosity normal
